#!/usr/bin/env bash

function api_client() {
	sess=$1
	shift

	url=$1
	shift

	method='get'
	if [[ $1 =~ ^(get|post|put|delete|GET|POST|PUT|DELETE)$ ]]; then
		method=$1
		shift
	fi

	url="$url/$1"
	shift
	http --session=$sess $method $url $@
	echo "http --session=$sess $method $url $@"
	#echo "curl -b cookies -c cookies -X $method $url $@"
}

function sand(){
	api_client 'sand' 'http://sand.api.appnexus.com' $@
}

function prod(){
	api_client 'prod' 'http://api.appnexus.com' $@
}
