#!/usr/bin/env bash

ln -sF ~/code/dotFiles/.bash_profile ~/.bash_profile
ln -sF ~/code/dotFiles/.vimrc ~/.vimrc
ln -sF ~/code/dotFiles/.gitconfig ~/.gitconfig
ln -sF ~/code/dotFiles/.gitignore_global ~/.gitignore_global
