#!/usr/bin/env bash

dirname="$PWD"

if [ -x "$dirname/private/update" ]; then
	source $dirname/private/update
fi


mkdir -p ~/.config
mkdir -p ~/.vim

for file in ./bash/*; do
	name=$(echo "$file" | grep -o '[^\/]*$');
	ln -sf "$dirname/bash/$name" "$HOME/.bash_$name"
done

ln -sf $dirname/vimrc ~/.vimrc
ln -sf $dirname/dir_colors ~/.dir_colors
ln -sf $dirname/gitconfig ~/.gitconfig
ln -sf $dirname/gitignore_global ~/.gitignore_global
ln -sf $dirname/ackrc ~/.ackrc
ln -sf $dirname/jshintrc ~/.jshintrc
ln -sf $dirname/tmux.conf ~/.tmux.conf
ln -sf $dirname/rtorrent.rc ~/.rtorrent.rc
ln -sf $dirname/powerline ~/.config/
ln -sf $dirname/xmobarrc ~/.xmobarrc

ln -snf $dirname/vim/colors ~/.vim/colors
ln -snf $dirname/vim/after ~/.vim/after
ln -snf $dirname/bin ~/bin


source ~/.bash_profile

# if this is the first run we are going to need to install vundle
if [[ ! -d "$HOME/.vim/bundle/Vundle.vim" ]];then
	mkdir -p "$HOME/.vim/bundle";
	git clone https://github.com/gmarik/Vundle.vim.git "$HOME/.vim/bundle/Vundle.vim"
fi

# if this is the first run we are going to need to install tmuxifier
if [[ ! -d "$HOME/.tmuxifier" ]];then
	git clone https://github.com/jimeh/tmuxifier.git "$HOME/.tmuxifier";
fi

vim +BundleInstall +qall
