#!/usr/bin/env bash

if [ -x "$dirname/private/update" ]; then
	source $dirname/private/update
fi

dirname="$PWD"

mkdir -p ~/.config
mkdir -p ~/.vim

for file in ./bash/*; do
	name=$(echo "$file" | ack -o '[^\/]*$');
	ln -sf "$dirname/bash/$name" "$HOME/.bash_$name"
done

ln -sf $dirname/vimrc ~/.vimrc
ln -sf $dirname/gitconfig ~/.gitconfig
ln -sf $dirname/gitignore_global ~/.gitignore_global
ln -sf $dirname/ackrc ~/.ackrc
ln -sf $dirname/jshintrc ~/.jshintrc
ln -sf $dirname/tmux.conf ~/.tmux.conf
ln -sf $dirname/powerline ~/.config/

if [ ! -d "$HOME/.vim/colors" ]; then
	ln -s $dirname/vim/colors ~/.vim/colors
fi

if [ ! -d "$HOME/.vim/after" ]; then
	ln -s $dirname/vim/after ~/.vim/after
fi

if [ ! -d "$HOME/bin" ]; then
	ln -s $dirname/bin ~/bin
fi


source ~/.bash_profile
vim +BundleInstall +qall
