#!/usr/bin/env bash

dataDir="$HOME/code/dotFiles/anx-api"

function mycurl(){
	result=$(http --print=hb --session=$@) &&
	status=$(echo "$result" | head -n 1 | ack -o -1 '[1-5][0-9]{2}')
}

function api_client() {

	sess=$1
	shift

	anx_version=$1
	shift 

	member=$1
	shift

	anx_obj_id=$1
	shift

	url=$1
	shift

	authfile=$1
	shift

	method='get'
	if [[ $1 =~ ^(get|post|put|head|delete|GET|POST|PUT|HEAD|DELETE)$ ]]; then
		method=$1
		shift
	fi

	if [[ ! -z "$anx_version" ]]; then
		url="$url/$anx_version"
	fi

	service="$1"
	route="$url/$service"
	shift
	

	if [[ ! -z "$member" ]]; then
		if [[ $route =~ \? ]]; then
			route="$route&member_id=$member"
		else
			route="$route?member_id=$member"
		fi
	fi

	if [[ ! -z "$anx_obj_id" ]]; then
		if [[ $route =~ \? ]]; then
			route="$route&id=$anx_obj_id"
		else
			route="$route?id=$anx_obj_id"
		fi
	fi

	echo "$method $route"
	mycurl $sess $method $route $@

	if [[ "$status" == "401" ]]; then
		if [[ ! -s "$authfile" ]]; then
			echo "unable to authenticate.  create $authfile to enable auto-login"
			return 1
		fi
		printf 'logging in...'
		mycurl $sess 'POST' "$url/auth" @$authfile

		if [[ "$status" != "200" ]]; then
			echo 'unable to authenticate'
			return 1
		else
			echo ' done.'
		fi
		
		#now do it again
		mycurl $sess $method $route $@
	fi

	local body=$(echo "$result" | tail -n 1)
	if $do_save; then 
		local anx_property_name=$(echo "$body" | json response.dbg_info.output_term)
		body=$(echo "$body" | json "response.$anx_property_name")
		echo "{\"$anx_property_name\":$body}" | python -m json.tool >  "$service.$anx_obj_id.json" 
	elif [ -t 1 ]; then # use colors if no being piped
		echo "$body" | prettyjson | less -R
	else 
		echo "$body" | python -m json.tool
	fi

	if $do_edit; then 
		printf 'Saving...'
		 vim "$service.$anx_obj_id.json" &&
			mycurl $sess PUT $route $@ "@$service.$anx_obj_id.json"
		printf ' done.\n'
	fi
}

function parse_api(){
	local OPTIND
	while getopts ":rsei:m:v:" opt; do
	  case $opt in
		v)
			ANX_SAND_API_VERSION="$OPTARG"
			;;
		m)
			ANX_SAND_API_MEMBER="$OPTARG"
			;;
		i)
			ANX_SAND_API_ID="$OPTARG"
			;;
		r)
			ANX_SAND_API_VERSION=''
			ANX_SAND_API_MEMBER=''
			rm -rf ~/.httpie
			echo 'member and version cleared!'
			return 1
			;;
		s)
			do_save=true
			;;
		e)
			do_save=true
			do_edit=true
			;;
		\?)
		  echo "Invalid option: -$OPTARG" >&2
			return
		  ;;
		:)
		  echo "Option -$OPTARG requires an argument." >&2
		  return
		  ;;
	  esac
	done
	shift $((OPTIND-1))

	if [[ "$#" -ge 1 ]]; then
		httpie_args+=" $1"
		shift
		parse_api "$@";
	else
		:
	fi

}

function sand(){
	local do_edit=false
	local do_save=false
	local httpie_args
	local ANX_SAND_API_ID

	if parse_api "$@"; then 
		api_client 'sand' "$ANX_SAND_API_VERSION" "$ANX_SAND_API_MEMBER" "$ANX_SAND_API_ID" "http://sand.api.appnexus.com" "$dataDir/auth-sand.private" $httpie_args
	fi
}

function prod(){
	api_client 'prod' "$ANX_PROD_API_MEMBER" "$ANX_SAND_API_ID" 'http://api.appnexus.com' "$dataDir/auth-prod.private" $@
}

