#!/usr/bin/env bash

username='mchevett'
srcDir="/Users/$username/adnxs/hbui"
destDir="$username@$username.devnxs.net:/home/$username/"

rsync -vhrtlCi --progress --exclude-from=./sync_ignore.txt --delete --rsh='ssh' "$srcDir" "$destDir"
