#!/usr/bin/env bash

username='mchevett'
srcDir="/Users/$username/adnxs/hbui"
destDir="$username@$username.devnxs.net:/home/$username/"
cmd="rsync -hrtlC --out-format='%n' --exclude-from=sync_ignore.txt --delete --rsh='ssh' $srcDir $destDir"
cmd="(echo 'Syncing... ' && $cmd && echo 'done.') || echo 'FAIL!'"

echo "Watching $srcDir"
fswatch "$srcDir" "$cmd"
