#! /usr/bin/env bash

alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

alias ll="ls -lh --color"
alias lastcmd="history | tail -n 2 | head -n 1 | sed -r 's/^\s+[0-9]+\s+//g'  | pbcopy"
