#! /usr/bin/env bash

HISTSIZE=10000
export EDITOR='vim'

PRIVATE_MODULE=~/code/dotFiles/private/

set -o vi
complete -C aws_completer aws
gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"

PATH=/usr/local/sbin:$PATH
PATH=~/bin:$PATH
PATH=~/private-bin:$PATH
PATH=~/private-bin/nvim-linux64/bin:$PATH
PATH=/usr/local/share/python:$PATH
PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:/home/mchevett/go/bin"

export ANDROID_HOME=$HOME/Android/Sdk
export ANDROID_SDK_ROOT=$HOME/Android/Sdk

if [ -d "$ANDROID_HOME/tools/bin/" ]; then
   PATH=$ANDROID_HOME/tools/bin/:$PATH
fi

if [ -d "$ANDROID_HOME/platform-tools/" ]; then
   PATH=$ANDROID_HOME/platform-tools/:$PATH
fi

if [ -f "$PRIVATE_MODULE/bash_profile.sh" ]; then
	source "$PRIVATE_MODULE/bash_profile.sh"
fi

function __runIfPresent(){
	[[ -f "$1" && -s "$1" ]] && source "$1";
}

for file in ~/.bash_*; do
	if [[ ! $file =~ bash_profile|bash_history$ ]]; then
		__runIfPresent "$file"
	fi
done
