#! /usr/bin/env bash

if hash gdate 2>/dev/null; then
	if [ -f $(brew --prefix)/etc/bash_completion ]; then
		. $(brew --prefix)/etc/bash_completion
		source $(brew --prefix)/etc/bash_completion.d/git-prompt.sh
		GIT_PS1_SHOWUPSTREAM="auto"
		GIT_PS1_SHOWCOLORHINTS="yes"
		GIT_PS1_SHOWUNTRACKEDFILES='yes'
		export PROMPT_COMMAND='__git_ps1 "\u@\h \W" "\\\$ ";'
	fi
fi
